### ISSUE TITLE
cheat sheet on txt/csv

### ISSUE THREAD

**Issue by catalinbostan** [sara-nl/Intro-to-HPC#1]
we don't need excel for this simple cheat sheet ...also dropping space in filename--linux is different at parsing spaces...
[cheat_sheet.txt](https://github.com/sara-nl/Intro-to-HPC/files/8069053/cheat_sheet.txt)

**Comment by mvsurf** [comment]
Thanks Catalin, really appreciated. I've added the txt to the main repo.
